name: AcademyBukkit
description: Allow server-side customizations of the behaviors of AcademyCraft 
version: 1.0.1
softdepend: [PlotSquared, Residence]
main: net.berry64.academyBukkit.AcademyBukkit

commands:
  academybukkit:
    description: information about this plugin and mod